/*!
 * @header CFTTransactionRecord.h
 *
 * @brief The Transaction Record object is created (usually by a Transaction object)
 * to represent the record of a past transaction.
 *
 * @copyright 2019 CardFlight Inc. All rights reserved.
 */

#import <Foundation/Foundation.h>
#import "CFTEnum.h"
#import "CFTConstants.h"

@class CFTTransactionParameters;
@class CFTCardReaderInfo;
@class CFTCardInfo;
@class CFTAvsResponse;

@interface CFTTransactionRecord : NSObject

/*!
 * @property uuid
 * @brief UUID of the Transaction
 * Added in 4.7.0
 */
@property (nonatomic, readonly, strong, nullable) NSUUID *uuid;

/*!
 * @property createdAt
 * @brief Date when the Transaction was created
 * Added in 4.7.0
 */
@property (nonatomic, readonly, strong, nonnull) NSDate *createdAt;

/*!
 * @property result
 * @brief Result of the Transaction
 * Added in 4.7.0
 */
@property (nonatomic, readonly, assign) CFTTransactionResult result;

/*!
 * @property declineMessage
 * @brief Decline message (Only populated if the result was declined)
 * Added in 4.7.0
 */
@property (nonatomic, readonly, copy, nullable) NSString *declineMessage;

/*!
 * @property error
 * @brief Error that occurred (Only populated if the result was errored)
 * Added in 4.7.0
 */
@property (nonatomic, readonly, strong, nullable) NSError *error;

/*!
 * @property cardInfo
 * @brief Card Info used by the Transaction
 * Added in 4.7.0
 */
@property (nonatomic, readonly, strong, nullable) CFTCardInfo *cardInfo;

/*!
 * @property cardToken
 * @brief Card Token generated by the Transaction
 * Added in 4.1.0
 */
@property (nonatomic, readonly, strong, nullable) NSString *cardToken;


/*!
 * @property transactedAt
 * @brief Date when the Transaction was processed
 * Updated in 4.5.0
 */
@property (nonatomic, readonly, strong, nullable) NSDate *transactedAt;

/*!
 * @property chargeId
 * @brief CardFlight charge ID from a transaction
 * Added in 4.1.0
 */
@property (nonatomic, readwrite, copy, nullable) NSString *chargeId;

/*!
 * @property referenceId
 * @brief Reference number of the transaction
 * Updated in 4.1.0
 */
@property (nonatomic, readonly, copy, nullable) NSString *referenceId;

/*!
 * @property transactionParameters
 * @brief Transaction Parameters used by the Transaction
 * Added in 4.7.0
 */
@property (nonatomic, readonly, strong, nullable) CFTTransactionParameters *transactionParameters;

/*!
 * @property transactionType
 * @brief Type of Transaction
 * Added in 4.7.0
 */
@property (nonatomic, readonly, assign) CFTTransactionType transactionType;

/*!
 * @property cardReaderInfo
 * @brief Card Reader Info used by the Transaction
 * Added in 4.7.0
 */
@property (nonatomic, readonly, strong, nullable) CFTCardReaderInfo *cardReaderInfo;

/*!
 * @property signatureUrl
 * @brief URL of the signature data
 * Added in 4.7.0
 */
@property (nonatomic, readonly, strong, nullable) NSURL *signatureUrl;

/*!
 * @property transactionState
 * @brief Current state of the transaction
 * Added in 4.1.0
 */
@property (nonatomic, readonly, assign) CFTApiTransactionState apiTransactionState;

/*!
 * @property avsResponse
 * @brief Avs result of the transaction
 * Added in 4.5.0
 */
@property (nonatomic, readonly, strong, nullable) CFTAvsResponse *avsResponse;

/*!
 * @property authCodes
 * @brief AuthCodes of a transaction.
 * Added in 4.7.0
 */
@property (nonatomic, readonly, strong, nullable) NSArray<NSString *> *authCodes;

@end
